services:
  - type: web
    name: estoque-statiot-api
    runtime: python
    region: ohio
    plan: free
    buildCommand: cd backend && python3 -m pip install -r requirements.txt
    startCommand: cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT