services:
  - type: web
    name: estoque-statiot-api
    runtime: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: python3 -m venv .venv && .venv/bin/python -m pip install --upgrade pip && .venv/bin/pip install -r requirements.txt
    startCommand: .venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT